# Generated by Django 5.1 on 2024-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilmoitukset', '0003_ad_image_alter_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
